// <auto-generated />
using System;
using GradeCalculationApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GradeCalculationApplication.Migrations
{
    [DbContext(typeof(GradeCalculationContext))]
    [Migration("20210918195945_AddedBaseEntitiesForGradeCalculation")]
    partial class AddedBaseEntitiesForGradeCalculation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GradeCalculationApplication.Models.Entities.CourseEntity", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseCredit")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StudentEntityStudentID")
                        .HasColumnType("int");

                    b.HasKey("CourseID");

                    b.HasIndex("StudentEntityStudentID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("GradeCalculationApplication.Models.Entities.StudentEntity", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GradeCalculationApplication.Models.Entities.CourseEntity", b =>
                {
                    b.HasOne("GradeCalculationApplication.Models.Entities.StudentEntity", null)
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentEntityStudentID");
                });

            modelBuilder.Entity("GradeCalculationApplication.Models.Entities.StudentEntity", b =>
                {
                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
